repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: pretty-format-json
        args: ["--no-sort-keys", "--autofix"]
  - repo: local
    hooks:
      - id: include-what-you-use
        name: include-what-you-use
        entry: scripts/run_iwyu.sh
        language: script
        files: \.(c|cc|cpp|cxx|h|hh|hpp|hxx)$
        pass_filenames: true
